# This is a basic workflow to help you get started with Actions

name: CI

# We just need on pull request because there should not be a
# direct edit to the main branch.
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v2

      # First we validate the json in the snippets
      # - name: Validate JSON
      #   uses: OrRosenblatt/validate-json-action@0.1.0
      #   with:
          # leave the schema key empty to use default
          # we want to target all json scripts only
          # json:  ./snippets/*.json 
      # Next we build and test the typescript files
      - uses: actions/checkout@v2
      - name: install node v12
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: yarn install
        run: yarn install
      - name: tsc
        uses: icrawl/action-tsc@v1
        #TODO: add typescript test to project and to this CI/CD
      - name: set up stall
        uses: HaaLeo/publish-vscode-extension@v1
        with:
          pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          registryUrl: https://marketplace.visualstudio.com

          
